### ISSUE TITLE
Created file name was incorrect.

### ISSUE THREAD

**Issue by shinriyo** [franzsilva/flutter_launcher_icons#13]
I did `flutter pub pub run flutter_launcher_icons:main` command.

And, `AppIcon-20x20@1x.png` was created in `ios/Runner/Assets.xcassets/`folders. (iOS)
but original flutter icon name is `Icon-App-20x20@1x.png`
So, app icon wasn't replaced.

**Comment by MarkOSullivan94** [comment]
Good spot! Thanks for raising this issue.

**Comment by felipecesar00** [comment]
I had the same problem. I had to change manually. Also I noticed there is a default size of flutter the package isn't covering: _Icon-App-1024x1024@1x_. Would be great to also add this case to the package

**Comment by MarkOSullivan94** [comment]
@felipecesar00 noted your suggestion. Will try and get that merged in before pushing a new update to the Dart package.

I think @franzsilva will be giving me permission to push updates to the Dart package, so hopefully you'll see these changes soon!

**Comment by felipecesar00** [comment]
Great @MarkOSullivan94! Thanks for the feedback :)

**Comment by MarkOSullivan94** [comment]
@felipecesar00 added with this commit https://github.com/franzsilva/flutter_launcher_icons/commit/2ce74e0710786c9496f8305122d7f385532a84e5

**Comment by MarkOSullivan94** [comment]
Published this in v0.2.1
