### ISSUE TITLE
IOS icon

### ISSUE THREAD

**Issue by enzotiezzi** [franzsilva/flutter_launcher_icons#16]
The IOS icon is not being updated.

but that's because the file `ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json` has not been updated with the `AppIcon` name as the new Icon is created.

Example: 

    {
      "size" : "20x20",
      "idiom" : "iphone",
      "filename" : "Icon-App-20x20@2x.png",
      "scale" : "2x"
    }

if you simply change the filename to `AppIcon` instead of `Icon-App` in all occurencies, the icon will change and eveything will be fine.

Solution:

    {
      "size" : "20x20",
      "idiom" : "iphone",
      "filename" : "AppIcon-20x20@2x.png",
      "scale" : "2x"
    }
(change in all occurencies)

**Comment by MarkOSullivan94** [comment]
@enzotiezzi thank you for reporting this issue. It has been reported already (#13) and I've merged in a fix into the GitHub project (#15). 

However the dart package itself has not been updated. @franzsilva gave me permission for this GitHub project recently however I cannot do anything until @franzsilva gives me permission to update the dart package or updates it himself.

I haven't heard from him recently so I'm debating creating an entire new dart package to release updates for everyone.

**Comment by MarkOSullivan94** [comment]
Publish v0.2.1 which should fix this.
