### ISSUE TITLE
project/ios/Runner/Assets.xcassets: error: None of the input catalogs contained a matching stickers icon set or app icon set named "Icon-App"

### ISSUE THREAD

**Issue by arashbi** [franzsilva/flutter_launcher_icons#22]
So I used this to generate the icons - which was pretty sweet, thank you very much.
Trying to create the IOS app, I got this error:
project/ios/Runner/Assets.xcassets: error: None of the input catalogs contained a matching stickers icon set or app icon set named  "Icon-App".
I have very little knowledge of iOS development, so I have no idea what is going on.

**Comment by MarkOSullivan94** [comment]
@arashbi should be fixed in 0.3.2
