### ISSUE TITLE
App Icons appearing as boxes

### ISSUE THREAD

**Issue by kevinrobert3** [franzsilva/flutter_launcher_icons#29]
I tried to add the package and I think it somehow ruined all other icons in my app(actual icons like the menu icon to open the app drawer). All icons now display as little crossed boxes. Now am trying to rebuild it and all but still nothing. Kindly tell me if this is an issue and if anyone has experienced it. I need a solution real quick

**Comment by MarkOSullivan94** [comment]
Hi @kevinrobert3 thanks for reporting this issue! 

Have you got any screenshots of this? It's the first I've heard of this happening.

Could you also show your pubspec.yaml?
