### ISSUE TITLE
should we use dev_dependencies?

### ISSUE THREAD

**Issue by sethladd** [franzsilva/flutter_launcher_icons#3]
In the README, you say to put the package under "dependencies", but that's intended to list packages required to run the app.

I think we can use dev_dependencies for this util script?

**Comment by franzsilva** [comment]
Yes, that sounds right. We can use dev_dependencies. Will work on that

**Comment by MarkOSullivan94** [comment]
Just tested this out and it works fine listed under dev_dependencies. Updated the README to include this change among others.

**Comment by MarkOSullivan94** [comment]
@sethladd README changes have been merged in so dev_dependencies is used instead. Think this can be closed now?

**Comment by sethladd** [comment]
thanks!
