### ISSUE TITLE
Confusing description of the ios/android options

### ISSUE THREAD

**Issue by dmjones** [franzsilva/flutter_launcher_icons#30]
I find the description in the README confusing:

> android/ios: True / False OR <Icon Name> - Specify whether or not you want to override the existing launcher icon or create a new one and switch to it (while keeping the old one there)

Firstly, it's confusing what 'true' and 'false' do. Does 'true' override or does it create a new one?

I'm also confused about what happens if I specify an Icon Name. Does that mean you read a particular file? Or does it somehow name the resulting files differently?

**Comment by MarkOSullivan94** [comment]
Hi @dmjones, thanks for reporting this. Apologies for the description being unclear.

True - Override the default existing Flutter launcher icon
False - Ignore making launcher icons for this platform
<FileName> - This will generate a new launcher icons for the platform with the name you specify, without removing the old default existing Flutter launcher icon.

If this makes more sense, I'll try and reword the description.

**Comment by dmjones** [comment]
That makes sense, thanks for explaining. 

Perhaps the options would be more intuitive if you split them? Separating the true/false enabling from the overriding might allow for more descriptive keywords?

**Comment by MarkOSullivan94** [comment]
@dmjones updated the README for v0.5.1 release. More than happy to add more to it if you have further suggestions?
